version: "3"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube    
    ports:
      - "9001:9000"
    expose:
      - 9001
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube.db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db

  db:
    container_name: sonarqube.db
    image: postgres
    ports:
      - 5423:5432
    expose:
      - 5423
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DATABASE: sonar    
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data

networks: 
  sonarnet:      
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_logs:
  postgresql:
  postgresql_data: